package com.example.svip;

import android.app.*;
import android.os.*;
import android.content.*;
import android.net.Uri;
import android.provider.Settings;
import android.graphics.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
  static final String QQ_GROUP="467063305";
  static final String APP_VERSION="2.4.3", ANALYTICS_BASE="http://47.103.127.205:8080";
  static final String HOST="gw.xiaocantech.com", PATH="/rpc", SERVER="SilkwormVip";
  static final String CHECK="VipRightsService.GetBrandCardExpiredTime", CLAIM="VipRightsService.GrabExtraBrandCard";
  TextView status, log; EditText time; Button select, verify, start, stop; final List<Uri> harUris=new ArrayList<>(); volatile boolean cancelled; volatile File logFile;
  final ExecutorService pool=Executors.newFixedThreadPool(5); final Handler ui=new Handler(Looper.getMainLooper());

  public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);buildUi();setupAnalyticsConsent();}
  TextView text(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setPadding(0,8,0,8);return v;}
  Button button(String s){Button b=new Button(this);b.setText(s);return b;}
  void buildUi(){
    ScrollView sc=new ScrollView(this); LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(36,36,36,36);sc.addView(root);
    TextView title=text("SVIP 大牌券定时助手",24); title.setTextColor(0xff1367d1);root.addView(title);
    root.addView(text("可一次选择全部 HAR，应用会自动识别小蚕会话；文件仅在本机读取。",14));
    select=button("1. 一键导入全部 HAR");root.addView(select);status=text("尚未导入会话",16);root.addView(status);
    verify=button("2. 只验证会话（不会领券）");root.addView(verify);
    root.addView(text("目标时间（本机时间）",15));time=new EditText(this);time.setText("09:30:00.000");time.setSingleLine();root.addView(time);
    start=button("3. 开始定时任务");root.addView(start);stop=button("停止");stop.setEnabled(false);root.addView(stop);
    root.addView(text("执行参数：精确发包点（-500、-300、-200、-150、-100、-60、-30、-10、0、+30、+60、+100、+200、+400ms）；4条连接，成功立即停止，限流时不追加突发重试。",13));
    CheckBox analytics=new CheckBox(this);analytics.setText("允许匿名统计（启动、版本、任务结果和错误；不上传HAR、账号或登录凭证）");analytics.setChecked(prefs().getBoolean("analytics_enabled",false));root.addView(analytics);analytics.setOnCheckedChangeListener((v,checked)->{prefs().edit().putBoolean("analytics_enabled",checked).putBoolean("analytics_asked",true).apply();if(checked)track("app_open","enabled_in_settings");});
    EditText feedback=new EditText(this);feedback.setHint("使用建议或问题（不会上传HAR和登录信息）");feedback.setMaxLines(4);root.addView(feedback);Button sendFeedback=button("提交反馈");root.addView(sendFeedback);sendFeedback.setOnClickListener(v->{String message=feedback.getText().toString().trim();if(message.length()<2){Toast.makeText(this,"请至少输入2个字",Toast.LENGTH_SHORT).show();return;}sendFeedback(message,feedback,sendFeedback);});
    TextView groupTitle=text("QQ 交流群："+QQ_GROUP,18);groupTitle.setTextColor(0xff1367d1);groupTitle.setPadding(0,28,0,4);root.addView(groupTitle);
    Button copyGroup=button("复制群号 "+QQ_GROUP);root.addView(copyGroup);
    root.addView(text("扫码加入交流群，获取使用帮助和版本更新：",14));
    ImageView groupQr=new ImageView(this);groupQr.setAdjustViewBounds(true);groupQr.setContentDescription("QQ交流群二维码，群号"+QQ_GROUP);try{Bitmap full=BitmapFactory.decodeResource(getResources(),R.drawable.qq_group_qr);if(full!=null){int left=Math.max(0,full.getWidth()*8/100),top=Math.max(0,full.getHeight()*16/100),right=Math.min(full.getWidth(),full.getWidth()*92/100),bottom=Math.min(full.getHeight(),full.getHeight()*72/100);groupQr.setImageBitmap(Bitmap.createBitmap(full,left,top,right-left,bottom-top));}}catch(Exception e){groupQr.setImageResource(R.drawable.qq_group_qr);}root.addView(groupQr,new LinearLayout.LayoutParams(-1,-2));
    copyGroup.setOnClickListener(v->{ClipboardManager cm=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(ClipData.newPlainText("QQ群号",QQ_GROUP));Toast.makeText(this,"群号已复制："+QQ_GROUP,Toast.LENGTH_SHORT).show();});
    log=text("运行日志\n",13);log.setTextIsSelectable(true);root.addView(log);setContentView(sc);
    select.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,7);});
    verify.setOnClickListener(v->runVerify()); start.setOnClickListener(v->runSchedule()); stop.setOnClickListener(v->{cancelled=true;append("已请求停止。\n");});
  }
  protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==7&&c==RESULT_OK&&d!=null){harUris.clear();if(d.getClipData()!=null){for(int i=0;i<d.getClipData().getItemCount();i++)addHar(d.getClipData().getItemAt(i).getUri());}else if(d.getData()!=null)addHar(d.getData());status.setText("已导入 "+harUris.size()+" 个文件，等待自动识别");append("已导入 "+harUris.size()+" 个文件；验证时将自动查找 gw.xiaocantech.com/rpc。\n");}}
  void addHar(Uri u){if(u==null)return;harUris.add(u);try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}}
  synchronized void beginLog(String kind){File base=getExternalFilesDir(null);File dir=new File(base==null?getFilesDir():base,"logs");dir.mkdirs();logFile=new File(dir,kind+"_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.CHINA).format(new Date())+".txt");append("日志文件："+logFile.getAbsolutePath()+"\n");}
  synchronized void append(String s){String line="["+new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS",Locale.CHINA).format(new Date())+"] "+s;ui.post(()->log.append(line));if(logFile!=null)try(FileOutputStream o=new FileOutputStream(logFile,true)){o.write(line.getBytes(StandardCharsets.UTF_8));}catch(Exception ignored){}}
  void busy(boolean x){ui.post(()->{select.setEnabled(!x);verify.setEnabled(!x);start.setEnabled(!x);stop.setEnabled(x);});}
  String readHar(Uri uri) throws Exception {try(InputStream in=getContentResolver().openInputStream(uri)){ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];for(int n;(n=in.read(b))>0;)o.write(b,0,n);return o.toString("UTF-8");}}
  Session load() throws Exception {if(harUris.isEmpty())throw new Exception("请先一键导入全部 HAR");int bad=0;for(Uri uri:harUris){try{JSONArray es=new JSONObject(readHar(uri)).getJSONObject("log").getJSONArray("entries");for(int i=es.length()-1;i>=0;i--){JSONObject r=es.getJSONObject(i).getJSONObject("request");if(("https://"+HOST+PATH).equals(r.optString("url"))){Map<String,String> h=new LinkedHashMap<>();JSONArray hs=r.getJSONArray("headers");for(int j=0;j<hs.length();j++){JSONObject x=hs.getJSONObject(j);h.put(x.getString("name"),x.getString("value"));}JSONObject body=new JSONObject(r.getJSONObject("postData").getString("text"));long id=body.getLong("silk_id");append("自动识别成功："+uri.getLastPathSegment()+"，silk_id 尾号 "+String.valueOf(id).replaceAll(".*(.{4})$","$1")+"\n");return new Session(h,id);}}}catch(Exception ignored){bad++;}}throw new Exception("扫描 "+harUris.size()+" 个文件后未找到可用小蚕会话（无法解析 "+bad+" 个）");}
  void runVerify(){busy(true);pool.submit(()->{beginLog("verify");try{Session s=load();Result r=null;Exception last=null;for(int i=1;i<=3;i++)try{r=s.call(CHECK,99);break;}catch(Exception e){last=e;append("会话验证第"+i+"次网络异常："+e+"\n");sleep(300);}if(r==null)throw last;append(String.format(Locale.CHINA,"会话验证：发送=%s；接收=%s；HTTP=%d；业务码=%d；延迟=%.1fms；服务器Date=%s；消息=%s\n",clock(r.sent),clock(r.received),r.http,r.code,r.ms,r.serverDate,r.msg));track(r.http==200&&r.code==0?"verify_success":"verify_failure","code_"+r.code);}catch(Exception e){append("验证失败："+e.getMessage()+"\n");track("verify_failure",e.getClass().getSimpleName());}finally{busy(false);}});}
  void runSchedule(){cancelled=false;busy(true);pool.submit(()->{beginLog("claim");ExecutorService workers=null;try{
    track("task_started","");
    Session base=load();Result vr=null;Exception last=null;for(int i=1;i<=3;i++)try{vr=base.call(CHECK,99);break;}catch(Exception e){last=e;append("会话验证第"+i+"次网络异常："+e+"\n");sleep(300);}if(vr==null)throw last;
    append(String.format(Locale.CHINA,"会话验证：发送=%s；接收=%s；HTTP=%d；业务码=%d；延迟=%.1fms；服务器Date=%s\n",clock(vr.sent),clock(vr.received),vr.http,vr.code,vr.ms,vr.serverDate));if(vr.http!=200||vr.code!=0)throw new Exception("会话已失效，请重新抓取 HAR");
    final long[] offsets={-500,-300,-200,-150,-100,-60,-30,-10,0,30,60,100,200,400};
    long target=nextTarget(time.getText().toString());append("配置：目标="+fmt(target)+"；精确发包点=[-500,-300,-200,-150,-100,-60,-30,-10,0,+30,+60,+100,+200,+400]ms；截止=目标后3000ms；连接=4；连接超时=0.6s；响应超时=0.8s\n");append("等待目标时间 "+fmt(target)+"\n");while(!cancelled&&System.currentTimeMillis()<target-6000)sleep(Math.min(500,target-6000-System.currentTimeMillis()));if(cancelled)return;
    Session[] ss={base,load(),load(),load()};workers=Executors.newFixedThreadPool(4);List<Future<Result>> warm=new ArrayList<>();for(Session s:ss)warm.add(workers.submit(()->s.call(CHECK,99)));double best=99999;for(int i=0;i<warm.size();i++){try{Result r=warm.get(i).get();best=Math.min(best,r.ms);append(String.format(Locale.CHINA,"预热连接%d：HTTP=%d；业务码=%d；延迟=%.1fms；发送=%s；接收=%s\n",i+1,r.http,r.code,r.ms,clock(r.sent),clock(r.received)));}catch(Exception e){append("预热连接"+(i+1)+"失败："+e+"；继续执行\n");}}
    append(String.format(Locale.CHINA,"预热4条连接，最快 %.1fms；计划首包=%s（-80ms）\n",best,clock(target+offsets[0])));while(!cancelled&&System.currentTimeMillis()<target+offsets[0]-3)sleep(1);if(cancelled)return;
    long targetNano=System.nanoTime()+(target-System.currentTimeMillis())*1000000L,deadline=target+3000;boolean[] used=new boolean[4];CompletionService<Attempt> done=new ExecutorCompletionService<>(workers);int inflight=0,attempts=0,received=0,errors=0,slot=0;boolean ok=false;List<Double> lat=new ArrayList<>();Map<Integer,Integer> codes=new TreeMap<>();
    while(!cancelled&&(slot<offsets.length||inflight>0)){
      long now=System.nanoTime();
      if(!ok&&slot<offsets.length&&now>=targetNano+offsets[slot]*1000000L){int free=-1,limit=offsets[slot]<0?3:4;for(int i=0;i<limit;i++)if(!used[i]){free=i;break;}if(free>=0){final int si=free,no=++attempts;final long scheduled=System.currentTimeMillis(),planned=offsets[slot++];used[si]=true;inflight++;done.submit(()->{try{return new Attempt(no,si,scheduled,planned,ss[si].call(CLAIM,99),null);}catch(Exception e){return new Attempt(no,si,scheduled,planned,null,e);}});}else if(now>targetNano+(offsets[slot]+60)*1000000L){append("跳过发包点"+(offsets[slot]>=0?"+":"")+offsets[slot]+"ms：全部连接忙，避免延迟补发形成突发流量。\n");slot++;}}
      Future<Attempt> f;while((f=done.poll())!=null){Attempt a=f.get();inflight--;used[a.session]=false;if(a.error!=null){errors++;append("第"+a.no+"次；计划点="+(a.planned>=0?"+":"")+a.planned+"ms；调度="+clock(a.scheduled)+"；网络异常="+a.error+"；继续执行既定发包点\n");continue;}Result r=a.result;received++;lat.add(r.ms);codes.put(r.code,codes.containsKey(r.code)?codes.get(r.code)+1:1);append(String.format(Locale.CHINA,"第%d次；计划点=%+dms；调度=%s；实际发送=%s；相对目标=%+dms；接收=%s；HTTP=%d；业务码=%d；延迟=%.1fms；消息=%s；服务器Date=%s\n",a.no,a.planned,clock(a.scheduled),clock(r.sent),r.sent-target,clock(r.received),r.http,r.code,r.ms,r.msg,r.serverDate));if(r.code==0)ok=true;else if(r.code==50008)append("服务器提示请求过于频繁；保持后续既定发包点，不追加即时重试。\n");}
      if(ok&&inflight==0)break;if(slot>=offsets.length&&inflight==0)break;if(System.currentTimeMillis()>deadline&&inflight==0)break;Thread.yield();
    }
    if(ok)append("领取成功，停止重试。\n");else append(cancelled?"任务已停止。\n":"已到重试截止时间，停止。\n");double min=99999,max=0,sum=0;for(double x:lat){min=Math.min(min,x);max=Math.max(max,x);sum+=x;}append("汇总：发起="+attempts+"；收到="+received+"；网络异常="+errors+"；业务码统计="+codes+(lat.isEmpty()?"":"；延迟最快="+String.format(Locale.CHINA,"%.1f",min)+"ms；最慢="+String.format(Locale.CHINA,"%.1f",max)+"ms；平均="+String.format(Locale.CHINA,"%.1f",sum/lat.size())+"ms")+"；成功="+ok+"\n");track(ok?"claim_success":"claim_finished",ok?"success":(cancelled?"cancelled":"not_success"));if(errors>0)track("network_error","count_"+errors);
  }catch(Exception e){append("运行失败："+e+"\n");track("claim_finished",e.getClass().getSimpleName());}finally{if(workers!=null)workers.shutdownNow();busy(false);}});}
  SharedPreferences prefs(){return getSharedPreferences("privacy",MODE_PRIVATE);}
  String installId(){String id=prefs().getString("install_id","");if(id.length()<32){id=UUID.randomUUID().toString();prefs().edit().putString("install_id",id).apply();}return id;}
  void setupAnalyticsConsent(){SharedPreferences p=prefs();if(p.getBoolean("analytics_asked",false)){if(p.getBoolean("analytics_enabled",false))track("app_open","");return;}new AlertDialog.Builder(this).setTitle("帮助改进应用").setMessage("是否允许发送匿名使用数据？只统计启动、版本、任务结果和错误类型，不上传HAR、账号、Cookie、Token或其他登录凭证。你可以在主页面随时关闭。").setPositiveButton("允许",(d,w)->{p.edit().putBoolean("analytics_asked",true).putBoolean("analytics_enabled",true).apply();track("first_launch","");}).setNegativeButton("暂不允许",(d,w)->p.edit().putBoolean("analytics_asked",true).putBoolean("analytics_enabled",false).apply()).show();}
  void track(String event,String outcome){if(!prefs().getBoolean("analytics_enabled",false))return;pool.submit(()->{try{JSONObject j=baseAnalytics();j.put("event",event);j.put("outcome",outcome);postJson("/api/analytics/events",j);}catch(Exception ignored){}});}
  JSONObject baseAnalytics()throws Exception{JSONObject j=new JSONObject();j.put("install_id",installId());j.put("app_version",APP_VERSION);j.put("android_version",Build.VERSION.RELEASE);j.put("channel","direct");return j;}
  void sendFeedback(String message,EditText field,Button button){button.setEnabled(false);pool.submit(()->{try{JSONObject j=baseAnalytics();j.put("message",message);postJson("/api/analytics/feedback",j);ui.post(()->{field.setText("");button.setEnabled(true);Toast.makeText(this,"反馈已提交，谢谢",Toast.LENGTH_SHORT).show();});}catch(Exception e){ui.post(()->{button.setEnabled(true);Toast.makeText(this,"提交失败，请检查网络后重试",Toast.LENGTH_SHORT).show();});}});}
  void postJson(String path,JSONObject body)throws Exception{byte[] data=body.toString().getBytes(StandardCharsets.UTF_8);HttpURLConnection c=(HttpURLConnection)new URL(ANALYTICS_BASE+path).openConnection();c.setConnectTimeout(1500);c.setReadTimeout(1500);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");try(OutputStream o=c.getOutputStream()){o.write(data);}int code=c.getResponseCode();if(code<200||code>=300)throw new IOException("HTTP "+code);InputStream in=c.getInputStream();if(in!=null)in.close();c.disconnect();}
  static long nextTarget(String s)throws Exception{SimpleDateFormat f=new SimpleDateFormat("HH:mm:ss.SSS",Locale.CHINA);Date t=f.parse(s);Calendar now=Calendar.getInstance(),x=Calendar.getInstance();Calendar q=Calendar.getInstance();q.setTime(t);x.set(Calendar.HOUR_OF_DAY,q.get(Calendar.HOUR_OF_DAY));x.set(Calendar.MINUTE,q.get(Calendar.MINUTE));x.set(Calendar.SECOND,q.get(Calendar.SECOND));x.set(Calendar.MILLISECOND,q.get(Calendar.MILLISECOND));if(x.getTimeInMillis()<=now.getTimeInMillis())x.add(Calendar.DAY_OF_MONTH,1);return x.getTimeInMillis();}
  static String fmt(long x){return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS",Locale.CHINA).format(new Date(x));}static String clock(long x){return new SimpleDateFormat("HH:mm:ss.SSS",Locale.CHINA).format(new Date(x));}static void sleep(long x){try{Thread.sleep(Math.max(1,x));}catch(Exception ignored){}}
  static String md5(String s)throws Exception{MessageDigest m=MessageDigest.getInstance("MD5");byte[] b=m.digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder z=new StringBuilder();for(byte x:b)z.append(String.format("%02x",x));return z.toString();}
  static class Result{int http,code;double ms;String msg,serverDate,raw;long sent,received;Result(int h,int c,double m,String g,String d,String z,long s,long r){http=h;code=c;ms=m;msg=g;serverDate=d;raw=z;sent=s;received=r;}}
  static class Attempt{int no,session;long scheduled,planned;Result result;Exception error;Attempt(int n,int s,long q,long p,Result r,Exception e){no=n;session=s;scheduled=q;planned=p;result=r;error=e;}}
  static class Session{Map<String,String> headers;long silk;Session(Map<String,String> h,long s){headers=h;silk=s;}
    Result call(String method,int type)throws Exception{long ts=System.currentTimeMillis();String nonce=UUID.randomUUID().toString().replace("-","").substring(0,16);String route=md5((SERVER+"."+method).toLowerCase(Locale.ROOT));Map<String,String> h=new LinkedHashMap<>();for(Map.Entry<String,String> e:headers.entrySet()){String k=e.getKey().toLowerCase(Locale.ROOT);if(!k.equals("host")&&!k.equals("content-length")&&!k.equals("servername")&&!k.equals("methodname")&&!k.equals("x-ashe")&&!k.equals("x-garen")&&!k.equals("x-nami")&&!k.startsWith(":"))h.put(e.getKey(),e.getValue());}h.put("servername",SERVER);h.put("methodname",method);h.put("X-Garen",String.valueOf(ts));h.put("X-Nami",nonce);h.put("X-Ashe",md5(route+ts+nonce));JSONObject b=new JSONObject();b.put("silk_id",silk);b.put("type",type);b.put("app_id",20);byte[] data=b.toString().getBytes(StandardCharsets.UTF_8);long sent=System.currentTimeMillis(),st=System.nanoTime();HttpURLConnection c=(HttpURLConnection)new URL("https://"+HOST+PATH).openConnection();c.setConnectTimeout(600);c.setReadTimeout(800);c.setRequestMethod("POST");c.setDoOutput(true);for(Map.Entry<String,String> e:h.entrySet())c.setRequestProperty(e.getKey(),e.getValue());try(OutputStream o=c.getOutputStream()){o.write(data);}int http=c.getResponseCode();String serverDate=c.getHeaderField("Date");InputStream in=http>=400?c.getErrorStream():c.getInputStream();String raw="";if(in!=null){ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] x=new byte[4096];for(int n;(n=in.read(x))>0;)o.write(x,0,n);raw=o.toString("UTF-8");}long received=System.currentTimeMillis();double ms=(System.nanoTime()-st)/1e6;JSONObject j;try{j=new JSONObject(raw);}catch(Exception e){j=new JSONObject();}JSONObject q=j.optJSONObject("status");return new Result(http,q==null?-1:q.optInt("code",-1),ms,q==null?raw:q.optString("msg",""),serverDate,raw,sent,received);}
  }
}
